
struct AD14file
    Directory
    Notes
    StallMod
    UseCm
    InfModel
    IndModel
    AToler
    TLModel
    HLModel
    TwrShad
    ShadHWid
    T_Shad_Refpt
    AirDens
    KinVisc
    DTAero
    NumFoil
    Foils
    BldNodes
    Nodes
end

mutable struct AD15file
    #I'm storing the booleans as strings. :|
    Directory::Array{String}
    Notes::String
    Echo::String
    DTAero::String
    WakeMod::Int
    AFAeroMod::Int
    TwrPotent::Int
    TwrShadow::String
    TwrAero::String
    FrozenWake::String
    CavitCheck::String
    CompAA::String
    AA_InputFile::String
    AirDens::Float64
    KinVisc::Float64
    SpdSound::Float64
    Patm::Float64
    Pvap::Float64
    FluidDepth::Float64
    SkewMod::Int
    SkewModFactor::String
    TipLoss::String
    HubLoss::String
    TanInd::String
    AIDrag::String
    TIDrag::String
    IndToler::String
    MaxIter::Int
    DBEMT_Mod::Int
    tau1_const::Int
    OLAFInputFileName::String
    UAMod::Int
    FLookup::String
    AFTabMod::Int
    InCol_Alfa::Int
    InCol_Cl::Int
    InCol_Cd::Int
    InCol_Cm::Int
    InCol_Cpmin::Int
    NumAFfiles::Int
    Foils::Array{String}
    UseBlCm::String
    Blades::Array{String}
    NumTwrNds::Int
    TwrNds::Array
    SumPrint::String
    NBlOuts::Int
    BlOutNd::Array
    NTwOuts::Int
    TwOutNd::Array
    Outlist::Array{String}
    BldNd_BladesOut::Int
    BldNd_BlOutNd::Array{}
    NodeOutlist::Array{String}
 end

struct EDFile
     Directory
     Notes
     Echo
     Method
     DT
     Gravity
     FlapDOF1
     FlapDOF2
     EdgeDOF
     TeetDOF
     DrTrDOF
     GenDOF
     YawDOF
     TwFADOF1
     TwFADOF2
     TwSSDOF1
     TwSSDOF2
     PtfmSgDOF
     PtfmSwDOF
     PtfmHvDOF
     PtfmRDOF
     PtfmPDOF
     PtfmYDOF
     OoPDefl
     IPDefl
     BlPitch1
     BlPitch2
     BlPitch3
     TeetDefl
     Azimuth
     RotSpeed
     NacYaw
     TTDspFA
     TTDspSS
     PtfmSurge
     PtfmSway
     PtfmHeave
     PtfmRoll
     PtfmPitch
     PtfmYaw
     NumBl
     TipRad
     HubRad
     PreCone1
     PreCone2
     PreCone3
     HubCM
     UndSling
     Delta3
     AzimB1Up
     OverHang
     ShftGagL
     ShftTilt
     NacCMxn
     NacCMyn
     NacCMzn
     NcIMUxn
     NcIMUyn
     NcIMUzn
     Twr2Shft
     TowerHt
     TowerBsHt
     PtfmCMxt
     PtfmCMyt
     PtfmCMzt
     PtfmRefzt
     TipMass1
     TipMass2
     TipMass3
     HubMass
     HubIner
     GenIner
     NacMass
     NacYIner
     YawBrMass
     PtfmMass
     PtfmRIner
     PtfmPIner
     PtfmYIner
     BldNodes
     BldFile1
     BldFile2
     BldFile3
     TeetMod
     TeetDmpP
     TeetDmp
     TeetCDmp
     TeetSStP
     TeetHStP
     TeetSSSp
     TeetHSSp
     GBoxEff
     GBRatio
     DTTorSpr
     DTTorDmp
     Furling
     FurlFile
     TwrNodes
     TwrFile
     SumPrint
     OutFile
     TabDelim
     OutFmt
     TStart
     DecFact
     NTwGages
     TwrGagNd
     NBlGages
     BldGagNd
     Outlist
 end

struct EDBlade
     Directory
     Notes
     NBlInpSt
     BldFlDmp1
     BldFlDmp2
     BldEdDmp1
     FlStTunr1
     FlStTunr2
     AdjBlMs
     AdjFlSt
     AdjEdSt
     BldProps
     BldFl1Sh2
     BldFl1Sh3
     BldFl1Sh4
     BldFl1Sh5
     BldFl1Sh6
     BldFl2Sh2
     BldFl2Sh3
     BldFl2Sh4
     BldFl2Sh5
     BldFl2Sh6
     BldEdgSh2
     BldEdgSh3
     BldEdgSh4
     BldEdgSh5
     BldEdgSh6
 end

struct ADBlade
     Directory
     Notes
     NumBlNds
     BldProps
     BlSpn
     BlCrvAC
     BlSwpAC
     BlCrvAng
     BlTwist
     BlChord
     BlAFID
 end

#Aerodata structure, not to be confused with the airfoils input structure
 struct Aerodata
     Notes1
     Notes2
     NumAirfoils
     TableID
     Aoa_stall
     z1
     z2
     z3
     Aoa_0Cn
     dCn_0L
     Cn_stall_positive
     Cn_stall_negative
     Aoa_minCd
     Cd_min
     Polar
 end

 struct AirfoilInput
     InterpOrd
     NonDimArea
     NumCoords
     NumTabs
     Re
     UserProp
     InclUAdata
     alpha0
     alpha1
     alpha2
     eta_e
     C_nalpha
     T_f0
     T_V0
     T_p
     T_VL
     b1
     b2
     b5
     A1
     A2
     A5
     S1
     S2
     S3
     S4
     Cn1
     Cn2
     St_sh
     Cd0
     Cm0
     k0
     k1
     k2
     k3
     k1_hat
     x_cp_bar
     UACutout
     filtCutOff
     NumAlf
     Polar
 end

 struct AirfoilCoords
     NumCoords
     AirfoilReference
     Coordinates
 end
