
struct AD14file
    Directory
    Notes
    StallMod
    UseCm
    InfModel
    IndModel
    AToler
    TLModel
    HLModel
    TwrShad
    ShadHWid
    T_Shad_Refpt
    AirDens
    KinVisc
    DTAero
    NumFoil
    Foils
    BldNodes
    Nodes
end

mutable struct AD15file
    #I'm storing the booleans as strings. :|
    Directory::Array{String}
    Notes::String
    Echo::String
    DTAero::String
    WakeMod::Int
    AFAeroMod::Int
    TwrPotent::Int
    TwrShadow::String
    TwrAero::String
    FrozenWake::String
    CavitCheck::String
    CompAA::String
    AA_InputFile::String
    AirDens::Float64
    KinVisc::Float64
    SpdSound::Float64
    Patm::Float64
    Pvap::Float64
    FluidDepth::Float64
    SkewMod::Int
    SkewModFactor::String
    TipLoss::String
    HubLoss::String
    TanInd::String
    AIDrag::String
    TIDrag::String
    IndToler::String
    MaxIter::Int
    DBEMT_Mod::Int
    tau1_const::Int
    OLAFInputFileName::String
    UAMod::Int
    FLookup::String
    AFTabMod::Int
    InCol_Alfa::Int
    InCol_Cl::Int
    InCol_Cd::Int
    InCol_Cm::Int
    InCol_Cpmin::Int
    NumAFfiles::Int
    Foils::Array{String}
    UseBlCm::String
    Blades::Array{String}
    NumTwrNds::Int
    TwrNds::Array
    SumPrint::String
    NBlOuts::Int
    BlOutNd::Array
    NTwOuts::Int
    TwOutNd::Array
    Outlist::Array{String}
    BldNd_BladesOut::Int
    BldNd_BlOutNd::Array{}
    NodeOutlist::Array{String}
 end

 mutable struct BDFile
    Directory::Array{String}
    Notes::String
    Echo::String
    QuasiStaticInit::String
    rhoinf::Float64
    quadrature::Int
    refine
    n_fact
    DTBeam
    load_retries
    NRMax
    stop_tol
    tngt_stf_fd
    tngt_stf_comp
    tngt_stf_pert
    tngt_stf_difftol
    RotStates::String
    member_total::Int
    kp_total::Int
    membernumber::Array{}
    geomparams::Array{Float64,2}
    order_elem::Int
    BldFile::String
    UsePitchAct::String
    PitchJ::Float64
    PitchK::Float64
    PitchC::Float64
    SumPrint::String
    OutFmt::String
    NNodeOuts::Int
    OutNd::Array{Int}
    Outlist::Array{String}
    NodeOutlist::Array{String}
 end

mutable struct EDFile
     Directory::Array{String}
     Notes::String
     Echo::String
     Method::Int
     DT
     Gravity::Float64
     FlapDOF1::String
     FlapDOF2::String
     EdgeDOF::String
     TeetDOF::String
     DrTrDOF::String
     GenDOF::String
     YawDOF::String
     TwFADOF1::String
     TwFADOF2::String
     TwSSDOF1::String
     TwSSDOF2::String
     PtfmSgDOF::String
     PtfmSwDOF::String
     PtfmHvDOF::String
     PtfmRDOF::String
     PtfmPDOF::String
     PtfmYDOF::String
     OoPDefl::Float64
     IPDefl::Float64
     BlPitch1::Float64
     BlPitch2::Float64
     BlPitch3::Float64
     TeetDefl::Float64
     Azimuth::Float64
     RotSpeed::Float64
     NacYaw::Float64
     TTDspFA::Float64
     TTDspSS::Float64
     PtfmSurge::Float64
     PtfmSway::Float64
     PtfmHeave::Float64
     PtfmRoll::Float64
     PtfmPitch::Float64
     PtfmYaw::Float64
     NumBl::Int
     TipRad::Float64
     HubRad::Float64
     PreCone1::Float64
     PreCone2::Float64
     PreCone3::Float64
     HubCM::Float64
     UndSling::Float64
     Delta3::Float64
     AzimB1Up::Float64
     OverHang::Float64
     ShftGagL::Float64
     ShftTilt::Float64
     NacCMxn::Float64
     NacCMyn::Float64
     NacCMzn::Float64
     NcIMUxn::Float64
     NcIMUyn::Float64
     NcIMUzn::Float64
     Twr2Shft::Float64
     TowerHt::Float64
     TowerBsHt::Float64
     PtfmCMxt::Float64
     PtfmCMyt::Float64
     PtfmCMzt::Float64
     PtfmRefzt::Float64
     TipMass1::Float64
     TipMass2::Float64
     TipMass3::Float64
     HubMass::Float64
     HubIner::Float64
     GenIner::Float64
     NacMass::Float64
     NacYIner::Float64
     YawBrMass::Float64
     PtfmMass::Float64
     PtfmRIner::Float64
     PtfmPIner::Float64
     PtfmYIner::Float64
     BldNodes::Int
     BldFile1::String
     BldFile2::String
     BldFile3::String
     TeetMod::Int
     TeetDmpP::Float64
     TeetDmp::Float64
     TeetCDmp::Float64
     TeetSStP::Float64
     TeetHStP::Float64
     TeetSSSp::Float64
     TeetHSSp::Float64
     GBoxEff::Float64
     GBRatio::Float64
     DTTorSpr::Float64
     DTTorDmp::Float64
     Furling::String
     FurlFile::String
     TwrNodes::Int
     TwrFile::String
     SumPrint::String
     OutFile::Int
     TabDelim::String
     OutFmt::String
     TStart::Float64
     DecFact::Int
     NTwGages::Int
     TwrGagNd::Array{Int}
     NBlGages::Int
     BldGagNd::Array{Int}
     Outlist::Array{String}
     BldNd_BladesOut::Int
     BldNd_BlOutNd::Array{Int}
     NodeOutlist::Array{String}
 end

mutable struct EDBlade
     Directory
     Notes
     NBlInpSt
     BldFlDmp1
     BldFlDmp2
     BldEdDmp1
     FlStTunr1
     FlStTunr2
     AdjBlMs
     AdjFlSt
     AdjEdSt
     BldProps
     BldFl1Sh2
     BldFl1Sh3
     BldFl1Sh4
     BldFl1Sh5
     BldFl1Sh6
     BldFl2Sh2
     BldFl2Sh3
     BldFl2Sh4
     BldFl2Sh5
     BldFl2Sh6
     BldEdgSh2
     BldEdgSh3
     BldEdgSh4
     BldEdgSh5
     BldEdgSh6
 end

mutable struct ADBlade
     Directory
     Notes
     NumBlNds
     BldProps
     BlSpn
     BlCrvAC
     BlSwpAC
     BlCrvAng
     BlTwist
     BlChord
     BlAFID
 end

#Aerodata structure, not to be confused with the airfoils input structure
 struct Aerodata
     Notes1
     Notes2
     NumAirfoils
     TableID
     Aoa_stall
     z1
     z2
     z3
     Aoa_0Cn
     dCn_0L
     Cn_stall_positive
     Cn_stall_negative
     Aoa_minCd
     Cd_min
     Polar
 end

 struct AirfoilInput
     InterpOrd
     NonDimArea
     NumCoords
     NumTabs
     Re
     UserProp
     InclUAdata
     alpha0
     alpha1
     alpha2
     eta_e
     C_nalpha
     T_f0
     T_V0
     T_p
     T_VL
     b1
     b2
     b5
     A1
     A2
     A5
     S1
     S2
     S3
     S4
     Cn1
     Cn2
     St_sh
     Cd0
     Cm0
     k0
     k1
     k2
     k3
     k1_hat
     x_cp_bar
     UACutout
     filtCutOff
     NumAlf
     Polar
 end

 struct AirfoilCoords
     NumCoords
     AirfoilReference
     Coordinates
 end
